# Generated by Django 4.0 on 2022-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('first_option', models.CharField(max_length=30)),
                ('second_option', models.CharField(max_length=30)),
                ('third_option', models.CharField(max_length=30)),
                ('first_count', models.IntegerField(default=0)),
                ('second_count', models.IntegerField(default=0)),
                ('third_count', models.IntegerField(default=0)),
            ],
        ),
    ]
